### ISSUE TITLE
I could use the vendor blob used in the gta3xlwifi

### ISSUE THREAD

**Issue by midhunvnadh** [kristurek/python#1]
I saw your vendor blob for gta3xlwifi. Please... I am trying to port a non-gsi rom to the device. Can you give me the vendor blob ?

**Comment by kristurek** [comment]
I don't have anymore this repo, but you can easily extract "vendor blobs" using https://github.com/AndroidDumps/Firmware_extractor , https://github.com/ShivamKumarJha/android_tools

**Comment by midhunvnadh** [comment]
Thanks.

**Comment by midhunvnadh** [comment]
I am tying to port Ubuntu Touch to the Tablet.
If you are interested, We could work together.

You can contact me via: @hdanv on Telegram
Check my repos for the progress.
